# Generated by Django 5.0.1 on 2024-02-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Commentaire'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Article'},
        ),
    ]
