# Generated by Django 5.0.1 on 2024-02-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postuserlikes',
            options={'verbose_name': 'Like'},
        ),
    ]
